name: build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
