name: Setup Python

on:
  workflow_call:
    inputs:
      requirements_path:
        type: string
        description: "Path to the requirements.txt file"
        required: true

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r ${{ inputs.requirements_path }}
