name: test

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: code

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run tests
        run: python -m unittest src/app_test.py

  sonar-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_REF: ${{ github.ref }}

  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: code

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install snyk@latest

      - name: Snyk test
        run: npx snyk test --file=src/requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
